# Generated by Django 5.0.4 on 2024-05-01 11:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MainCode',
            fields=[
                ('ICD_main_code', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='ICD Main Code')),
                ('description', models.TextField(verbose_name='Description')),
            ],
        ),
        migrations.CreateModel(
            name='SubCode',
            fields=[
                ('ICD_sub_code', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='ICD Sub Code')),
                ('description', models.TextField(verbose_name='Description')),
                ('ICD_main_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ICD_codes.maincode', verbose_name='ICD Main Code')),
            ],
        ),
    ]
